#!/usr/bin/env sh
##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle
#
##############################################################################

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    expr "$link" : '/.*' > /dev/null && PRG="$link" || PRG=`dirname "$PRG"`/"$link"
done
saved=""`pwd`
cd "`dirname "$PRG"`" >/dev/null
APP_HOME="`pwd -P`"
cd "$saved"

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here without problematic nested quotes
DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'

# Locate java
if [ -n "$JAVA_HOME" ] ; then
  if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
    JAVACMD="$JAVA_HOME/jre/sh/java"
  else
    JAVACMD="$JAVA_HOME/bin/java"
  fi
  if [ ! -x "$JAVACMD" ] ; then
    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
    exit 1
  fi
else
  JAVACMD="java"
  which java >/dev/null 2>&1 || { echo "ERROR: JAVA_HOME is not set and no 'java' command could be found." >&2; exit 1; }
fi

# Execute Gradle
exec "$JAVACMD" $DEFAULT_JVM_OPTS \
  -Dorg.gradle.appname="$APP_BASE_NAME" \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain "$@"
